# Changes here will be overwritten by Copier
_commit: v0.3.4
_src_path: https://github.com/rvforest/copier-py-general
author: Robert Forest
author_email: rvforest@gmail.com
cli_command: nox-mcp
description: An MCP server for running nox sessions.
gh_owner: rvforest
has_cli: true
project_name: nox-mcp
py_min_version: '3.10'
